args:
  HOME_ASSISTANT_JWT: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3OWU5ZWNmYTAzZDU0MTEyOTk3YTllMWUwYTg0NTI0YiIsImlhdCI6MTY4ODg0NjUwNCwiZXhwIjoyMDA0MjA2NTA0fQ.tvX4raCXQQULYSYK1FuzDi7SlCC1e37CWXrmj69_hks"
  